---
# tasks file for simple_app_deployment
- name: create directory for simple_app
  file:
    path: "{{ remote_install_path }}"
    state: directory
- name: copy docker-compose
  template:
    src: docker-compose.yml
    dest: "{{ remote_install_path }}/{{ docker_compose_name }}"
    mode: 600
    owner: root
    group: root
- name: Run docker-compose
  docker_compose:
    project_src: "{{ remote_install_path }}"
    files:
      - "{{ docker_compose_name }}"
    state: present
    pull: true