version: "3"

networks:
  monitoring_logging:

services:
  simple_app:
    image: gapurinov/simple-app:latest
    container_name: simple_app_container
    ports:
      - "5000:5000"
    networks:
      - monitoring_logging
    logging:
      driver: "json-file"
      options:
        tag: "{{.ImageName}}|{{.Name}}"
    mem_limit: "256m"

  loki:
    image: grafana/loki:2.3.0
    container_name: loki_container
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - monitoring_logging
    mem_limit: "256m"

  promtail:
    image: grafana/promtail:2.3.0
    container_name: promtail_container
    volumes:
      - /var/log:/var/log
      - /var/lib/docker/containers/:/var/lib/docker/containers/
      - ./promtail.yml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
    networks:
      - monitoring_logging
    mem_limit: "256m"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana_container
    ports:
      - "3000:3000"
    networks:
      - monitoring_logging
    mem_limit: "256m"

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus_container
    ports:
    - 9090:9090
    command: --config.file=/etc/prometheus/prometheus.yml
    volumes:
    - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - monitoring_logging
    mem_limit: "256m"
